INSERT INTO RESOURCE (RESOURCE_NAME, RESOURCE_VALUE) VALUES ('User 1', '1000');
INSERT INTO RESOURCE (RESOURCE_NAME, RESOURCE_VALUE) VALUES ('User 2', '200');
INSERT INTO RESOURCE (RESOURCE_NAME, RESOURCE_VALUE) VALUES ('User 3', '3000');
INSERT INTO RESOURCE (RESOURCE_NAME, RESOURCE_VALUE) VALUES ('User 4', '4000');

INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('1', 'username', 'user0001');
INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('1', 'password', '****');
INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('1', 'location', '1');
INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('2', 'username', 'user0002');
INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('2', 'password', '****');
INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('2', 'location', '1');
INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('3', 'username', 'user0003');
INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('3', 'password', '!****');
INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('3', 'location', '2');
INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('4', 'username', 'user0004');
INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('4', 'password', '!****');
INSERT INTO RESOURCE_ATTRIBUTE (RESOURCE_ID, RESOURCE_ATTRIBUTE_NAME, RESOURCE_ATTRIBUTE_VALUE) VALUES ('4', 'location', '2');