CREATE TABLE RESOURCE(
  RESOURCE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  RESOURCE_NAME VARCHAR(16) NOT NULL,
  RESOURCE_VALUE VARCHAR(16) NOT NULL
);

CREATE TABLE RESOURCE_ATTRIBUTE(
  RESOURCE_ATTRIBUTE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  RESOURCE_ID BIGINT NOT NULL,
  RESOURCE_ATTRIBUTE_NAME VARCHAR(16) NOT NULL,
  RESOURCE_ATTRIBUTE_VALUE VARCHAR(16) NOT NULL
);

ALTER TABLE RESOURCE_ATTRIBUTE ADD FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE(RESOURCE_ID);